version: "3.8"

services:
  influxdb:
    image: influxdb:1.8
    platform: linux/arm/v7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_DB=sensor_data
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.5.25
    platform: linux/arm/v7
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  ble_to_influx:
    build: ./ble_to_influx
    container_name: ble_to_influx
    network_mode: host              # allows access to BLE device on the host
    privileged: true                # required for Bluetooth access
    volumes:
      - /var/run/dbus:/var/run/dbus # gives access to D-Bus for BLE
    devices:
      - /dev/hci0:/dev/hci0         # exposes Bluetooth adapter
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb_data:
  grafana_data:
