
services:
  gateway:
    build: ./gateway_server
    container_name: gateway_server
    privileged: true
    devices:
      - "/dev/rfcomm0:/dev/rfcomm0"
    environment:
      - UART_PORT=/dev/rfcomm0
      - BAUD_RATE=9600
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=your_token
      - INFLUX_ORG=your_org
      - INFLUX_BUCKET=mybucket
    restart: unless-stopped
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=your_org
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_TOKEN=your_token

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb

volumes:
  influxdb-data:
